config/routes.rb
Rails.application.routes.draw do
  resources :songs
  root 'songs#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
  
    if params['sort'].present?
       @songs = Song.where(:category => params['sort'])
    else
        @songs = Song.all
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :category, :game, :youtube)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaywardMusicPlayer</title>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :game %><br>
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :youtube %><br>
    <%= f.text_field :youtube %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h2><%= link_to 'Music Player', songs_path %></h2>

<div class="container">
<div class="row">

</div>
</div>
    <div class="col-xs-4">
        <table>
            <thread>
            <tr>
                <th>Categories</th>
                
            </tr>
            </thread>
            <tbody>
                
                    <tr><td><a href="?sort=Town">Town</a></td></tr>
                    <tr><td><a href="?sort=Field">Field</a></td></tr>
                    <tr><td><a href="?sort=Battle">Battle</a></td></tr>
                    <tr><td><a href="?sort=Boss">Boss</a></td></tr>
                    <tr><td><a href="?sort=Vehicle">Vehicle</a></td></tr>
                    <tr><td><a href="?sort=Sanctuary">Sanctuary</a></td></tr>
                    <tr><td><a href="?sort=Dramatic">Dramatic</a></td></tr>
                    <tr><td><a href="?sort=Primal">Primal</a></td></tr>
                    
                
            </tbody>
            
        </table>
    </div>
    <br>


    <div class="col-xs-8">
        <table>
        <thead>
            <tr>
            <th>Name</th>
            <th>Category</th>
            
            
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @songs.each do |song| %>
            <tr>
                <td><%= song.name %></td>
                <td><a href="?sort=<%= song.category %>"><%= song.category %></a></td>
                <td><button type="button" onclick="PlayMusic('<%= song.youtube %>')">Play</button></td>
                <td><button type="button" onclick="StopMusic()">Stop</button></td>
                <td><%= link_to 'View', song %></td>   
                <td><%= link_to 'Delete', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
    </div>
    <br>
    
   



    <%= link_to 'New Song', new_song_path %>


    <div id="player"></div>

    <!--<iframe id="ytplayer" type="text/html" width="0" height="0"
    src="http://www.youtube.com/embed/pEpIwurXnQQ?autoplay=1&loop=1&playlist=pEpIwurXnQQ"
    frameborder="0"/> -->



<script>

function PlayMusic(url) {
    
    document.getElementById("player").innerHTML = "<iframe id='ytplayer' type='text/html' width='0' height='0' src='http://www.youtube.com/embed/" + url + "?autoplay=1&autoplay=1&loop=1&playlist=" + url + "'  frameborder='0'/>";
    
}

function StopMusic() {
    document.getElementById("player").innerHTML = "";
}


  


</script>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @song.category %>
</p>

<p>
  <strong>Game:</strong>
  <%= @song.game %>
</p>

<p>
  <strong>Youtube:</strong>
  <%= @song.youtube %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>